### ISSUE TITLE
Write tests to check standards for entropy in VMs

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#268]
Standard for entropy in VMs can be found as [draft](https://github.com/SovereignCloudStack/docs/pull/24).

Is seems like we have to create cloud resources to test entropy compliance. If so, we should provide/reuse a framework to create/delete cloud resources, that can be reused in other tests. Furthermore, it must be ensured resources are cleaned up under all circumstances (including temporarily unavailable API etc.).

**Comment by cah-hbaum** [comment]
Draft can be found [here](https://github.com/SovereignCloudStack/docs/pull/24/files)
Addition to this can be found [here](https://github.com/SovereignCloudStack/standards/pull/266)

**Comment by cah-hbaum** [comment]
We had some talks in the Standardization Group about this.
The [Standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0101-v1-entropy.md) was updated last week to reflect the changes undertaken in Linux Kernel 5.17 / 5.18.

In general, the Standard is mostly sufficient for now, since all important parts are covered, but the whole problem described there is a bit outdated, if only newer kernel versions are used. But for (backwards) compatibility reasons, we should still keep it.
IMO some parts should also be changed a bit, e.g. the way how 'available' entropy is shown, since the available entropy isn't necessarily important, but instead the time in which it regenerates. Some more possible changes will be enumerated in the next comment.

A related, maybe more important issue would be some kind of investigation into the quality of these generated randomness in the new kernel, which, if not sufficient, could make hardware sources a necessity. If a document like this is created and if it should find its way into a standard, should be discussed in the meeting.

Compliance testing could be done the following way:
1) connect to an OpenStack instance
2) create a VM with an image and a flavor (we could check all image + flavor combinations here)
3) connect to the VM
4) check the kernel version of the VM
    1) Kernel < 5.18
        1) Check if havaged is installed
        2) Check if rng-tools / rng-utils is installed
        3) Jump to step 5)
    2) Kernel >= 5.18
        Everything should be fine
    3) If we want to be really meticulous, it would be best to start 2 processes, wherein 1 of them depletes entropy and the other one watches the available entropy
5) check available hardware entropy devices (based on the kernel optional or required)
    1) check the hardware devices
  `cat /sys/devices/virtual/misc/hw_random/rng_available`
    2) check the OpenStack flavor attributes for
`hw_rng:allowed = True`
and optionally
`hw_rng:rate_bytes = <Allowed amount of read bytes>
hw_rng:rate_period`
    3) check the OpenStack image attributes for
`hw_rng_model: virtio`
6) disconnect from the VM and remove everything built up from the environment

**Comment by cah-hbaum** [comment]
Some changes that should be included in the [Standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0101-v1-entropy.md):

- if "enough" entropy is available probably shouldn't be measured on the current available entropy, because depending on the kernel, it could be depleted fast and not be replenished for a long time (also, the number is hardcoded in newer kernels and therefore has no comparibility with newer kernels)
- add a few more information about entropy, how it is implemented in the Linux kernel and where the difference was between `/dev/random` and `/dev/urandom` and why this doesn't matter anymore
- especially, explain that the new kernel generates randomness via CPU jitters (basically hardware), which also works in VMs, since they have access to their respective CPU cores
-

**Comment by cah-hbaum** [comment]
Updated the test according to the changes in the standard from #297
