### ISSUE TITLE
You may offer additional `SCS-` flavors ...

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/standards#295]
Could this be confusing when moving between SCS clouds in the future?
I think it is important to see which flavors are SCS standard an which aren't. What do you think?

https://github.com/SovereignCloudStack/standards/blob/4aad551ed3c009d38c4ef7575200e7466de5cac9/Standards/scs-0100-v2-flavor-naming.md?plain=1#LL286-L286

**Comment by garloff** [comment]
We've had a discussion on whether the non-mandatory (and non-recommended?) Flavors should have a different prefix (e.g. `SCSx` instead of `SCS-`) to avoid users assuming that every `SCS-` flavor exists on all SCS clouds.
This is not ideal, as this will cause a rename when we specify additional mandatory flavors in the future (which will likely already exist on some clouds). Admittedly, it's not ideal either to make it non-obvious that SCS- flavors may exist only on some SCS clouds. We did not find a silver bullet ...

**Comment by garloff** [comment]
The more general approach is that we would like to develop a tool that analyses cloud and/or container deployments (either existing ones or ones described with terraform or heat or k8s deployment files or helm charts) and gives an assessment whether non-standardized features are used, limiting the portability to other SCS clouds/containers.

**Comment by mbuechse** [comment]
Maybe the sentence in question is just misleading:

> You may offer additional `SCS-` flavors, following the naming scheme and rules outlined here.

What is meant by additional? In addition to what? Of course everyone can offer flavors that conform to the naming scheme? The standard itself doesn't specify any mandatory flavors (this has been moved to a separate standard).

I suggest we remove the sentence.

**Comment by garloff** [comment]
Yes, let's move that sentence to the other standard (in case it's not there yet.)
