### ISSUE TITLE
Differentiation between Decision Records (DR) and Standards

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/standards#352]
During a meeting between Cloud&Heat and SecuStack, we had a short in discussion about the naming standard for Decision Records and Standards. Both document types are placed in the same location and their names are derived from the same naming scheme, which in our opinion leads to the following problems:

* DRs and Standards share a version numbering, which means that a standard could start at v2 (or even later) just because a DR was already created with/about the same topic. This could happen quite often, since DR often prepare and predate a Standard.
* The numbering could even become more confusing, if a new Standard version should be created and a DR is created beforehand again.
* To mitigate this with the current standardization, a Standard would need to have a different name as the DR. If this is the case, the documents could not be immediately seen as references to one another and the standard folder would be filled up with many documents that don't contain standards and are therefore not binding.

In our opinion, this should be changed in order to be more clear about the difference of Decision Records and Standards and therefore make the versioning more clear.

This issue should be seen as a ground for discussion and perhaps a way to change the Standardization-Standard in the end.

**Comment by markus-hentsch** [comment]
My two cents:

- the versioning part (`-vN-`) in the `scs-XXXX-vN-template.md` naming scheme is primarily relevant for actual standards since those are versioned and supersede one another
- when maintaining the DRs as separate files alongside the standards, splitting up the DR in multiple dedicated and versioned files over time does not make much sense; it would be better to keep exactly one (unversioned) DR file per standard that is maintained alongside the evolving standard versions
  - an alternative option would be to include the DR into the standards themselves as an appendix subsection
- regardless of where to put the DR (subsection in standard vs. dedicated file) the current `scs-XXXX-vN-template.md` template is a bad fit for decision records as it is primarily designed for standards, I'd expect a dedicated DR template file or section that specifies the DR structure and mandatory DR entry fields, like:
  - decision date
  - decision maker
  - decision
  - reasoning / rationale
  - etc.

**Comment by cah-hbaum** [comment]
I agree with these two cents.

**Comment by fkr** [comment]
Thanks @markus-hentsch and @cah-hbaum - just as the standards themselves are developed in a community driven process, so should also be the format and outline of decisions records.
We did unify the location a while ago (there used to be a standards and a decision folder) and this was discussed at length. However from my perspective that is just one of the minor points being addressed here - one of the major items (and @markus-hentsch points that out in this last bullet point) could and should be addressed. I would very much welcome a suggestion for such a template.

**Comment by cah-hbaum** [comment]
I created PR #441, where the discussion can be continued and expanded.
I also made a first suggestion for a new template there and also updated the old standard template.
