### ISSUE TITLE
[BUG] Extension syntax in flavor naming standard misleading

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#363]
SCS standard for [Server Flavors](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#generation-and-vendor) does not dictate to use suffix for CPU generation **always** in conjunction with suffix for CPU vendor. As it doesn't makes sense to use suffix for CPU generation without suffix of CPU vendor, SCS Flavor Standard should forbid this explicitly.

**Comment by mbuechse** [comment]
It turns out that the standard is merely hard to figure out correctly because the extensions syntax scheme uses brackets unevenly and in the subsections for the individual extensions the corresponding part of the syntax is not repeated. The PR will fix that. I will edit the title of this issue accordingly.
