### ISSUE TITLE
[Feature Request] How to test and visualize different RFC 2119 keyword in test scripts 

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#402]
SCS standards uses RFC2119 keyword, such as MUST, MUST NOT, SHOULD, SHOULD NOT and MAY, to define requirements to SCS compatible IaaS and KaaS. Whereas MUST and MUST NOT are binary and easy to test as well as to visualizes, we have to think how to tackle SHOULD, SHOULD NOT and MAY.

**Comment by anjastrunk** [comment]
### Keyword MUST and MUST NOT

#### Testing
Both keywords are binary:
- requirements labelled as **MUST** are fulfilled --> standards is meet
- requirements labelled as **MUST** are **not** fulfilled --> standards is **not** meet
- requirements labelled as  **MUST NOT** are **not** fulfilled --> standards is meet
- requirements labelled as  **MUST NOT** are fulfilled --> standards **not** is meet

#### Visualization
Both keywords are binary:
- requirements labelled as **MUST** are fulfilled --> green
- requirements labelled as  **MUST** are  **not** fulfilled --> red
- requirements labelled as  **MUST NOT** are **not** fulfilled --> green
- requirements labelled as  **NOT** are fulfilled --> red

**Comment by anjastrunk** [comment]
### Keyword SHOULD and SHOULD NOT

#### Testing
- requirements labelled as **SHOULD** are fulfilled --> standards is meet
- requirements labelled as **SHOULD** are **not** fulfilled --> standards is meet ??
- requirements labelled as  **SHOULD NOT** are **not** fulfilled --> standards is meet 
- requirements labelled as  **SHOULD NOT** are fulfilled --> standards is meet ??

_--> Question: SHOULD requirements do not have any impact on certificating_

#### Visualization
Both keywords are binary:
- requirements labelled as **SHOULD** are fulfilled --> green
- requirements labelled as  **SHOULD** are  **not** fulfilled --> yellow, including valid reason for not fulfilling the requirement. _Who evaluates goodness of reasons?_
- requirements labelled as  **SHOULD NOT** are **not** fulfilled --> green
- requirements labelled as  **SHOULD** are fulfilled --> yellow, including valid reason for fulfilling the requirement. _Who evaluates goodness of reasons?_

**Comment by anjastrunk** [comment]
### Keyword MAY and MAY NOT

???

**Comment by garloff** [comment]
As you say @anjastrunk:
* MUST and MUST NOT should produce errors
* SHOULD and SHOULD NOT should produce warnings
* MAY and MAY NOT may or may not produce a note/hint in the output of a test script, but no more

As someone trying to provide a compliant service, I would:
* Work through the MUST and MUST NOTs in order to become compliant.
* Work through the SHOULD and SHOULD NOTs in order to avoid trouble with future standards (some of the SHOULDs may become MUSTs in the future) and in order to achieve highest level of compatibility with other SCS providers. (The rationale here is that I actually save effort doing the SHOULDs as soon as I can, as changes later are more painful, at least for a greenfield setup.)
* I may look at the MAY assessment to get additional information on best practices or decisions that I may want to take deliberately.

**Comment by anjastrunk** [comment]
Do we have a standard/how to/best practice/developers guide for writing conformance tests?

**Comment by mbuechse** [comment]
> Do we have a standard/how to/best practice/developers guide for writing conformance tests?

It's on the agenda for SIG Std/Cerr

**Comment by mbuechse** [comment]
Closing this as it will be dealt with in #447.
