### ISSUE TITLE
[Other] Setup SCS test cluster at Cloud&Heat with Yaook

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#414]
Provide an additional SCS cluster for testing purposes as well as a playground to evaluate costs to make existing Openstack and K8S clusters SCS compliant. The test cluster MUST be set up with the open source Lifecycle Management Tool for OpenStack and K8S [Yaook](https://yaook.cloud/) to be not SCS compliant.

**Comment by cah-hbaum** [comment]
The Openstack cluster is already set up, we now need to check what exactly is necessary to make it compliant.
A good starting point would be to check the standards and tests already available in SCS.

**Comment by cah-hbaum** [comment]
We already setup a Yaook cluster on f1a, but its dormant for ~1,5 months now, since we're having problems with the network. To explain this a bit, it seems like a second network is needed to connect the virtual cluster to the provider network of f1a. This is required to setup an own internal provider network. I already talked with @horazont about this, but I personally had no idea that a second network was needed, so it wasn't created during my initial setup.

I already setup the new network, but it still needs to be integrated correctly.

The next step therefore would be to adapt this network to have a provider network in this Yaook test cluster.

**Comment by cah-hbaum** [comment]
Had some help from @markus-hentsch with the networking part and I'm working on it again now.

**Comment by cah-hbaum** [comment]
Deployment didn't come back up in a correct state, so I'm resetting the underlying K8s cluster right now in order to get the state of the Openstack cluster back.

**Comment by cah-hbaum** [comment]
Thanks to @markus-hentsch and another colleague, I was able to setup a Yaook OpenStack cluster which is able to be pinged from outside over the internal provider network.
I'm now going over to write a script in order to setup all necessary resources to make the cluster SCS-compliant.

**Comment by cah-hbaum** [comment]
If someone needs access to the cluster, just reach out to me (Matrix or mail) and I arrange something.

Closing for now, future work will be done in the follow up issues.
