### ISSUE TITLE
[Other] Adapt C&H test cluster to SCS KaaS default storage class (scs-0211)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#421]
Adapt C&H test cluster to [SCS KaaS default storage class (scs-0211)](https://docs-staging.scs.community/standards/scs-0211-v1-kaas-default-storage-class) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [x]  Update standard documentation with costs/cost estimation
- [x]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Updated the branch used for this with the informational content about the Kubernetes standards, which can be found [here](https://github.com/SovereignCloudStack/standards/tree/do-not-merge/scs-compliant-yaook/Informational/k8s).

Since the `Default Storage` standard isn't used in the `SCS K8s Compatible` certificate, we won't do the first point of this issue.
