### ISSUE TITLE
[Other] remove parts of image-md-check pertaining to deprecated certificate scopes?

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/standards#578]
The `image-md-check.py` has the possibility to check if all mandatory, recommended and suggested images are available.
This check (and list) seems unnecessary and even incorrect, since mandatory (and recommended) images are covered by the
`scs-0104-vX-images.yaml` and the test using this file as well as the standard `scs-0104-v1-standard-images`.

The current version of `image-md-check.py` seems to be from a time, when both these standards we're combined. I would suggest cleaning this old file up to make the test conform with the standard.

**Comment by mbuechse** [comment]
As of now, the check script can be used to check for all versions of the certificate scope "SCS-compatible IaaS" -- even the deprecated ones. For v3 as well as the current version v4, we invoke this script with `-s`, so it doesn't do the completeness check.

Removing the completeness check altogether would be a breaking change, because the CLI syntax would probably change, but most of all, we could no longer test for the obsolete scope versions. We can do it if everone is on board.
