### ISSUE TITLE
Monitoring  Userstories

### ISSUE THREAD

**Issue by matfechner** [SovereignCloudStack/standards#99]
As a SCS-Operator, 
I would like to monitor my OpenStack Infrastructure , OpenStack API and  my Storage Environment:
![Monitoring](https://user-images.githubusercontent.com/29937978/122398179-ed0d5b00-cf79-11eb-9921-48017e49d5f2.jpg)

**Comment by genofire** [comment]
i would like to use the https://Prometheus-Operator.dev [VictoriaMetrics](https://docs.victoriametrics.com/operator/VictoriaMetrics-Operator.html) which both suppords the custom resource definition ServiceMonitor and PodMonitor.

So that every installation bring this such Manifests (e.g. per Helm)


Same for logging with Logging Operator:
  - https://banzaicloud.com/docs/one-eye/logging-operator/
  - https://kube-logging.github.io/
Where are Flows with definition of parser (e.g. jdon,regex,... ) for log formats and shipping to any output (all that fluetd supports).

**Comment by mbuechse** [comment]
Has this been dealt with in some way?

**Comment by fkr** [comment]
@mbuechse yes - thanks for pinging here. this actually has been dealt with in many ways (since the colleagues from dNation did a lot of work on the monitoring stack).
